version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.server
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run ./cmd/server/main.go -b 0.0.0.0
  client:
    build:
      dockerfile: Dockerfile.client
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start
  db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: